# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/gomjellie/Documents/GitHub/Verilog/timer/timer.cache/wt [current_project]
set_property parent.project_path C:/Users/gomjellie/Documents/GitHub/Verilog/timer/timer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib C:/Users/gomjellie/Documents/GitHub/Verilog/timer/timer.srcs/sources_1/new/Timer.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/gomjellie/Documents/GitHub/Verilog/timer/timer.srcs/constrs_1/new/timerXdc.xdc
set_property used_in_implementation false [get_files C:/Users/gomjellie/Documents/GitHub/Verilog/timer/timer.srcs/constrs_1/new/timerXdc.xdc]


synth_design -top Timer -part xc7z020clg484-1


write_checkpoint -force -noxdef Timer.dcp

catch { report_utilization -file Timer_utilization_synth.rpt -pb Timer_utilization_synth.pb }
